# Generated by Django 3.0.7 on 2023-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Fee',
            field=models.TextField(default=1500),
            preserve_default=False,
        ),
    ]
